[project]
name = "haystack"
version = "0.1.0"
description = "Example project to show how to use haystack in pixi"
authors = ["Ruben Arts <ruben.arts@hotmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64"]

[system-requirements]
libc = "2.32"

[tasks]
start = "python main.py"

[dependencies]
python = "3.9"
pytorch = "2.0.0.*"
nltk = "3.8.1.*"
scikit-learn = ">=1.3.0"

[pypi-dependencies]
farm-haystack = ">=1.18"
